[package]
name = "tokio-chat-stream"
version = "0.1.0"
authors = ["Hamza Sajid"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio={version = "1", features = ["full"]}